name: baal-nf
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - bedtools=2.29
  - bowtie2=2.3
  - fastq-screen=0.14
  - fastqc=0.11
  - gat=1.3
  - multiqc=1.9
  - pandas=1.0
  - picard=2.23
  - pyranges
  - python=3.7
  - samtools=1.10
  - trim-galore=0.6
  - wget=1.20
  - nomkl=1.0
  - umi_tools=1.1
